version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pruebabackend:latest
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    image: pruebafrontend:latest
    ports:
      - "5173:80"  # frontend será accesible desde http://localhost:5173 o la IP pública:5173
    restart: always
    depends_on:
      - backend
