version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://backend:8000
    image: jgarcia9300/backend:latest
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    image: jgarcia9300/frontend:latest
    ports:
      - "5173:80"  # frontend será accesible desde http://localhost:5173 o la IP pública:5173
    restart: always
    depends_on:
      - backend
